apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-petclinic-rest.fullname" . }}-configmap
  labels:
    {{- include "spring-petclinic-rest.labels" . | nindent 4 }}
data:
  {{ (tpl (.Files.Glob "config/*").AsConfig . ) | nindent 2 }}
