apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-petclinic-rest.fullname" . }}
  labels:
    {{- include "spring-petclinic-rest.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spring-petclinic-rest.selectorLabels" . | nindent 6 }}
  progressDeadlineSeconds: 300
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/env-config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
        checksum/env-secret: {{ include (print $.Template.BasePath "/env-secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spring-petclinic-rest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring-petclinic-rest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "./run-java.sh" ]
          args: [ "--spring.config.location=file:/custom-config/" ]
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
#            - name: management
#              containerPort: 8081
#              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.containerPort | quote }}
            - name: SERVER
              value: {{ .Values.server | quote }}
            - name: PROFILE
              value: {{ .Values.profile | quote }}
            - name: JAVA_OPTIONS
              value: {{ .Values.javaOptions | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "spring-petclinic-rest.fullname" . }}-env-configmap
            - secretRef:
                name: {{ include "spring-petclinic-rest.fullname" . }}-env-secret
          startupProbe:
            httpGet:
              path: /livez
              port: {{ .Values.containerPort }}
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.containerPort }}
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.containerPort }}
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "spring-petclinic-rest.fullname" . }}-config
              mountPath: "/custom-config"
              readOnly: true
      volumes:
        - name: {{ include "spring-petclinic-rest.fullname" . }}-config
          configMap:
            name: {{ include "spring-petclinic-rest.fullname" . }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
