apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-petclinic-rest.fullname" . }}
  labels:
    {{- include "spring-petclinic-rest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
#    - port: 81
#      targetPort: 8081
#      protocol: TCP
#      name: management
  selector:
    {{- include "spring-petclinic-rest.selectorLabels" . | nindent 4 }}
