name: Deploy to Google Kubernetes Engine (GKE) Autopilot

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '422.0.0'

      - name: 'Set up Helm'
        uses: azure/setup-helm@v3
        with:
          version: '3.11.2'

      - name: 'Install gke-gcloud-auth-plugin'
        run: >
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: 'Connect to GKE'
        run: >
          gcloud container clusters get-credentials autopilot-cluster-1 --region europe-north1 --project kotoant

      - name: 'Deploy'
        run: >
          helm upgrade spring-petclinic-rest ./spring-petclinic-rest --atomic --install --timeout 5m --wait
